### ISSUE TITLE
Crash when I call WriteVideoFrame

### ISSUE THREAD

**Issue by Wil7070** [Twometer/CSVideo#1]
Hello, I'm trying you video library in 64 bits windows

`
            var writer = new CSVideo.Writer.VideoWriter("test0.avi");
            CSVideo.FFmpegLoader.Load(@"D:\Home\wil\0.dev\Sandbox\Accord test\WindowsFormsApp1\bin\Debug");
            writer.Open();

            Bitmap image = new Bitmap(320, 240);

            for (int i = 0; i < 240; i++)
            {
                // update image
                image.SetPixel(i, i, Color.Red);
                // add the image as a new frame of video file
                //writer.AddFrame(image);
                writer.WriteVideoFrame(image);
            }
            writer.Close();
`

It keeps crashing when it hit the " writer.WriteVideoFrame(image);"

![image](https://user-images.githubusercontent.com/89152727/130336607-8a21603a-e187-4818-a006-f085a29737fb.png)

Any idea how I can solve this?

Great work! one of the rare library on win64!!!!

Thanks

Wil

**Comment by Wil7070** [comment]
I found the issue, I needed to use 1920x1080

**Comment by tigrouind** [comment]
It's possible to use a custom resolution by setting `writer.Width` and `writer.Height` before calling `writer.Open()`
